=== ReunionDev/reunion-data/static/xml/quests.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" >
	<element name="quests">
		<complexType>
			<sequence minOccurs="1" maxOccurs="1">
				<element name="quest" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<choice minOccurs="0" maxOccurs="unbounded">
							<element name="rewards">
								<complexType>
									<choice minOccurs="0" maxOccurs="unbounded">
										<element name="experience"
											maxOccurs="1" minOccurs="0" type="positiveInteger">
										</element>
										<element name="lime"
											maxOccurs="1" minOccurs="0" type="positiveInteger">
										</element>
										<element name="item"
											maxOccurs="unbounded" minOccurs="0">
											<complexType>
												<attribute name="type" type="positiveInteger" use="required"/>
												<attribute name="count" type="positiveInteger" default="1"/>
											</complexType>
										</element>
									</choice>
								</complexType>
							</element>
							<element name="objectives">
								<complexType>
									<choice>
										<element name="kill"
											maxOccurs="unbounded" minOccurs="0">
											<complexType>
												<attribute name="type" type="positiveInteger" use="required"/>
												<attribute name="count" type="positiveInteger" default="1"/>
											</complexType>
										</element>
										<element name="points"
											maxOccurs="1" minOccurs="0" type="positiveInteger">
										</element>
									</choice>
								</complexType>
							</element>
							<element name="restrictions">
								<complexType>
									<choice minOccurs="0" maxOccurs="unbounded">
										<element name="level"
											maxOccurs="unbounded" minOccurs="0">
											<complexType>
												<attribute name="min" type="positiveInteger"/>
												<attribute name="max" type="positiveInteger"/>
											</complexType>
										</element>
										<element name="race"
											maxOccurs="5" minOccurs="0">
											<annotation>
												<documentation>0 = Bulkan
1 = Kailipton
2 = Aidia
3 = Human
4 = Hybrider</documentation>
											</annotation>
											<simpleType>
												<restriction base="integer">
													<minInclusive value="0" />
													<maxInclusive value="4" />
												</restriction>
											</simpleType>
										</element>
									</choice>
								</complexType>
							</element>
						</choice>
						<attribute name="id" type="positiveInteger"
							use="required" />
						<attribute name="name" type="string"
							use="required"/>
						<attribute name="type" use="required" >
							<annotation>
								<documentation>1 = Experience Quest
2 = Lime Quest
3 = Special Quest
4 = Points Quest</documentation>
							</annotation>
							<simpleType>
								<restriction base="integer">
									<minInclusive value="1" />
									<maxInclusive value="4" />
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
		<unique name="questKey">
		    <selector xpath="quest"/>
		    <field xpath="@id"/>
	  	</unique>
	</element>
</schema>

=== ReunionDev/reunion-data/static/xml/quests.xml
<?xml version="1.0" encoding="UTF-8"?>
<quests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quests.xsd">
	<quest id="1" type="2" name="S.King Chmero">
		<rewards>
			<item type="222"/>
		</rewards>
		<objectives>
			<kill type="228"/>
		</objectives>
		<restrictions>
			<level min="20" max="25"/>
			<race>0</race>
		
		</restrictions>
	</quest>
</quests>
